# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(485, 368)
        MainWindow.setMaximumSize(QtCore.QSize(485, 368))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.driverPathLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.driverPathLineEdit.setInputMask("")
        self.driverPathLineEdit.setText("")
        self.driverPathLineEdit.setObjectName("driverPathLineEdit")
        self.verticalLayout.addWidget(self.driverPathLineEdit)
        self.ChainOfEquationsLineEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.ChainOfEquationsLineEdit.setObjectName("ChainOfEquationsLineEdit")
        self.verticalLayout.addWidget(self.ChainOfEquationsLineEdit)
        self.startTaskButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startTaskButton.setObjectName("startTaskButton")
        self.verticalLayout.addWidget(self.startTaskButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ChemicalHelper"))
        self.driverPathLineEdit.setPlaceholderText(_translate("MainWindow", "absolute path to the geckodriver file"))
        self.ChainOfEquationsLineEdit.setPlaceholderText(_translate("MainWindow", "Enter your chain of chemical reactions (the separator between chemical compounds is a space, example: CO CH4 CH3I C2H6 CO2)"))
        self.startTaskButton.setText(_translate("MainWindow", "perform a task!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
